#!/usr/bin/env node
/**
 * retry_failed.js — Re-run extraction on failed posts
 *
 * Usage: node scripts/retry_failed.js <failed_log_path> [output_file]
 *
 * The failed log is generated by 02_extract_llm.js when posts fail extraction.
 * Output defaults to data/candidates/retry_YYYY-MM-DD.json
 */

'use strict';

const fs = require('fs');
const path = require('path');

const failedLogPath = process.argv[2];
if (!failedLogPath) {
    console.error('Usage: node scripts/retry_failed.js <failed_log_path> [output_file]');
    console.error('\nExample:');
    console.error('  node scripts/retry_failed.js data/candidates/2026-02-21_failed.json');
    process.exit(1);
}

// Load the failed log
let failedLog;
try {
    failedLog = JSON.parse(fs.readFileSync(failedLogPath, 'utf8'));
} catch (e) {
    console.error(`❌ Could not read failed log: ${failedLogPath}`);
    process.exit(1);
}

const { source_dir, posts } = failedLog;
console.log(`Retrying ${posts.length} failed posts from ${source_dir}...`);

// Build the retry command
const maxPosts = posts.length + 10; // Add buffer
const outputFile = process.argv[3] || `data/candidates/retry_${new Date().toISOString().split('T')[0]}.json`;

// Create a temp directory with symlinks to only the failed posts
const tempDir = path.join('data', 'raw', 'retry_temp');
if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir, { recursive: true });

// Clean temp dir
fs.readdirSync(tempDir).forEach(f => fs.unlinkSync(path.join(tempDir, f)));

// Symlink failed posts
let linked = 0;
for (const post of posts) {
    const srcPath = path.join(source_dir, post.file);
    const destPath = path.join(tempDir, post.file);
    if (fs.existsSync(srcPath)) {
        fs.symlinkSync(path.resolve(srcPath), destPath);
        linked++;
    } else {
        console.log(`  ⚠️  Source file not found: ${post.file}`);
    }
}

console.log(`Linked ${linked}/${posts.length} failed posts to ${tempDir}`);
console.log(`\nRunning extraction...`);

// Run extraction on temp dir
const { spawn } = require('child_process');
const child = spawn('node', [
    'pipeline/02_extract_llm.js',
    tempDir,
    outputFile,
], {
    MAX_POSTS: String(maxPosts),
    stdio: 'inherit',
});

child.on('close', (code) => {
    // Cleanup temp dir
    fs.readdirSync(tempDir).forEach(f => fs.unlinkSync(path.join(tempDir, f)));
    fs.rmdirSync(tempDir);

    if (code === 0) {
        console.log(`\n✅ Retry complete. Output: ${outputFile}`);
        console.log(`\nTo merge: node pipeline/03_enrich_candidates.js ${outputFile}`);
    } else {
        console.error(`\n❌ Extraction failed with code ${code}`);
    }
    process.exit(code);
});
